Manual Implementation

In [1]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[9, 2], [4, 4], [8, 6]])
print(A)
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)
# center columns by subtracting column means
C = A - M
print(C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[9 2]
 [4 4]
 [8 6]]
[7. 4.]
[[ 2. -2.]
 [-3.  0.]
 [ 1.  2.]]
[[ 7. -1.]
 [-1.  4.]]
[[ 0.95709203  0.28978415]
 [-0.28978415  0.95709203]]
[7.30277564 3.69722436]
[[ 2.49375235 -1.33461576]
 [-2.87127608 -0.86935245]
 [ 0.37752373  2.2039682 ]]


PCA Implementation

In [2]:
# Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[9, 2], [4, 4], [8, 6]])
print(A)
# create the PCA instance
pca = PCA(2)
# fit on data
pca.fit(A)
# access values and vectors
print(pca.components_)
print(pca.explained_variance_)
# transform data
B = pca.transform(A)
print(B)

[[9 2]
 [4 4]
 [8 6]]
[[-0.95709203  0.28978415]
 [ 0.28978415  0.95709203]]
[7.30277564 3.69722436]
[[-2.49375235 -1.33461576]
 [ 2.87127608 -0.86935245]
 [-0.37752373  2.2039682 ]]
