# NumPy Essential Training: 1 Foundations of NumPy

## Chapter 1 : Overview

In [1]:
2+8*5

42

## Chapter 2 : Numpy array types and creating Numpy Arrays

### Array types and conversions between types

In [2]:
import numpy as np

In [4]:
integers=np.array([10,20,30,40,50])

In [5]:
integers

array([10, 20, 30, 40, 50])

In [6]:
integers[0]

10

In [7]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [8]:
integers[0]=21.5
integers

array([21, 20, 30, 40, 50])

In [9]:
integers.dtype

dtype('int32')

In [10]:
smallerIntegers=np.array(integers,dtype=np.int8)

In [12]:
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [13]:
integers.nbytes

20

In [14]:
overflow = np.array([127,128,129], dtype = np.int8)
overflow

array([ 127, -128, -127], dtype=int8)

In [16]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])

In [17]:
floats

array([1.2, 2.3, 3.4, 5.1, 8.3])

In [18]:
floats.dtype

dtype('float64')

### Multidimensional array

In [19]:
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
nums[0,0]

1

In [22]:
nums[1,4]

10

In [23]:
nums.ndim

2

In [24]:
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [25]:
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
multi_arr[1,0,2]

9

### Creating arrays from Lists and other Python structures

In [27]:
first_list=[1,2,3,4,5,6,7,8,9,10]

In [28]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [29]:
first_array=np.array(first_list)

In [30]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
second_list=[1,2,3,-1.23,50,128000.56,4.56]

In [33]:
second_array=np.array(second_list)

In [34]:
second_array.dtype

dtype('float64')

In [35]:
third_list=['Ann',111111,'Peter',111112,'Susan',111113,'John',111114]


In [36]:
third_array=np.array(third_list)

In [37]:
third_array

array(['Ann', '111111', 'Peter', '111112', 'Susan', '111113', 'John',
       '111114'], dtype='<U11')

In [38]:
first_tuple =(5,10,15,20,25,30)

In [39]:
array_from_tuple=np.array(first_tuple)
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [40]:
array_from_tuple.dtype

dtype('int32')

In [41]:
multi_dim_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]] 

In [42]:
arr_from_multi_dim_list=np.array(multi_dim_list)

In [43]:
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Intrisic NumPy array creation

In [44]:
integers_array=np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
integers_second_array=np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [47]:
integers_third_array=np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [48]:
first_floats_arr=np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [49]:
second_floats_arr=np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [50]:
first_rand_arr=np.random.rand(10)
first_rand_arr

array([0.28083474, 0.72100694, 0.49540719, 0.63129895, 0.95275235,
       0.95169323, 0.78251022, 0.69581257, 0.00405148, 0.57213105])

In [51]:
second_rand_arr=np.random.rand(4,4)
second_rand_arr

array([[0.83787471, 0.95592772, 0.54018326, 0.95119388],
       [0.02367659, 0.65404243, 0.63859117, 0.98532049],
       [0.48937791, 0.23079885, 0.70746353, 0.07578554],
       [0.87183243, 0.54870318, 0.13721802, 0.33023857]])

In [52]:
third_rand_arr=np.random.randint(0,100,20)
third_rand_arr

array([38, 56, 75, 20, 61, 28, 88,  6, 68, 17, 11, 25, 40, 15, 63, 79, 46,
       41, 17, 32])

### Creating arrays filled with constant values

In [53]:
first_z_array=np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

In [54]:
second_z_array=np.zeros((4,5))
second_z_array


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
first_ones_array=np.ones(6)
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [56]:
second_ones_array=np.ones((7,8))
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
third_ones_array=np.ones((4,5),dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [58]:
first_fill_array=np.empty(10,dtype=int)
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [59]:
first_full_array=np.full(5,10)
first_full_array

array([10, 10, 10, 10, 10])

In [60]:
second_full_array=np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

###  Finding the shape and size of an array

In [61]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
second_arr=np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [63]:
third_arr=np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [64]:
np.shape(first_arr)

(20,)

In [65]:
np.shape(second_arr)

(10, 2)

In [66]:
np.shape(third_arr)

(2, 2, 2)

In [67]:
np.size(first_arr)


20

In [69]:
np.size(second_arr)

20

In [70]:
np.size(third_arr)

8

## Chapter 3 : Manipulate Numpy arrays


### Adding, removing and sorting elements

In [71]:
first_arr=np.array([1, 2, 3, 5])
first_arr

array([1, 2, 3, 5])

In [72]:
new_first_arr=np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [73]:
second_arr=np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [74]:
new_second_arr=np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [75]:
third_arr=np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [76]:
del_arr=np.delete(third_arr,4)
del_arr

array([1, 2, 3, 4])

In [77]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([15,  0, 19, 12, 16,  6,  6,  9,  7, 11,  2, 12,  4,  2,  0, 14, 16,
        3, 17, 15])

In [78]:
print(np.sort(integers_arr))

[ 0  0  2  2  3  4  6  6  7  9 11 12 12 14 15 15 16 16 17 19]


In [79]:
integers_2dim_arr=np.array([[3, 2, 5,7, 4], [5, 0, 8,3, 1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [80]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [81]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
colors

array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue',
       'red'], dtype='<U6')

In [82]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']


### Copies and views

In [83]:
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [84]:
students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

id of students_ids_number 1717033159632
id of students_ids_number_reg 1717033159632


In [85]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [87]:
students_ids_number_cp=students_ids_number.copy()
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [88]:
print(students_ids_number_cp==students_ids_number)

[ True  True  True  True  True  True  True  True]


In [89]:
print ("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))

id of students_ids_number 1717033159632
id of students_ids_number_cp 1717033159440


In [90]:
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [92]:
students_ids_number_v=students_ids_number.view()

In [94]:
students_ids_number_v[0]=2000
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [95]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]


### Reshaping Arrays 

In [96]:
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
second_arr=np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
third_arr=np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [99]:
fourth_arr=np.reshape(first_arr,(4,4))

ValueError: cannot reshape array of size 12 into shape (4,4)

In [100]:
fifth_arr=np.reshape(first_arr,(3,2,2))
print(fifth_arr)
print("Dimensions of fifth_arr is ",fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is  3


In [102]:
sixth_arr=np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [103]:
seventh_arr_flat=np.reshape(sixth_arr,-1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [104]:
eighth_arr_flat=sixth_arr.flatten()
print("eighth_arr_flat:",eighth_arr_flat)
ninth_arr_rav=sixth_arr.ravel()
print("ninth_arr_rav:",ninth_arr_rav)

eighth_arr_flat: [1 2 3 4 5 6]
ninth_arr_rav: [1 2 3 4 5 6]


In [106]:
eighth_arr_flat[0]=100

In [108]:
ninth_arr_rav[0]=200

In [109]:
print("eighth_arr_flat:",eighth_arr_flat)
print("ninth_arr_rav:",ninth_arr_rav)
print("sixth_arr:",sixth_arr)

eighth_arr_flat: [100   2   3   4   5   6]
ninth_arr_rav: [200   2   3   4   5   6]
sixth_arr: [[200   2]
 [  3   4]
 [  5   6]]


In [110]:
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
twodim_arr[1,1]

5

In [112]:
twodim_arr[1]

array([4, 5, 6, 7])

In [113]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [114]:
threedim_arr[0,2,3]

13

In [115]:
threedim_arr[2,-1,-1]

59

In [116]:
onedim_arr=np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [118]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [119]:
onedim_arr[-3:]

array([7, 8, 9])

In [121]:
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [131]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
twodim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [127]:
twodim_arr[1,:]

array([4, 5, 6, 7])

In [128]:
twodim_arr[:,2]

array([ 2,  6, 10])

### Joining and splitting ararys

In [132]:
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print("first_arr",first_arr)
print("second_arr",second_arr)

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


In [133]:
con_arr=np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [134]:
third_2darr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
third_2darr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [135]:
fourth_2darr=np.array([[11,12,13,14,15], [16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [136]:
con2d_arr = np.concatenate((third_2darr,fourth_2darr),axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [137]:
st_arr = np.stack((first_arr,second_arr))
st_arr 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [138]:
hst_arr=np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [139]:
vst_arr=np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [141]:
fifth_arr=np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [142]:
sp_arr=np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [143]:
print(sp_arr[1])

[4 5 6]


In [144]:
sp_arr=np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [147]:
np.hsplit(third_2darr,5)


[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [148]:
vs_arr=np.vsplit(third_2darr,2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

## Chapter 4 : Functions and Operations


### Arithmetic operations

In [149]:
a=np.arange(1,11)
b=np.arange(21,31)
print("a",a)
print("b",b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [150]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [151]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [152]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [153]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [154]:
a**b

array([          1,     4194304,  -346101685,           0,   167814181,
       -1543503872,    17998615,           0, -1635065239,  1073741824])

In [155]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [156]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [157]:
np.subtract(b,a)


array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [158]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [159]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [160]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [161]:
np.power(a,b)

array([          1,     4194304,  -346101685,           0,   167814181,
       -1543503872,    17998615,           0, -1635065239,  1073741824])

In [162]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

### Broadcasting

In [163]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [165]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [166]:
c=np.arange(1,3)
c

array([1, 2])

In [167]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [168]:
d=np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [169]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [170]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

### Aggregate functions

In [171]:
first_arr=np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [172]:
second_arr=np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [173]:
third_arr=np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [174]:
first_arr.sum()

550

In [175]:
second_arr.sum()

450

In [177]:
third_arr.sum()

550

In [178]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [179]:
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [180]:
first_arr.prod()

1704722432

In [181]:
second_arr.prod()

-1786839040

In [182]:
third_arr.prod()

1704722432

In [183]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [184]:
np.average(first_arr)

55.0

In [185]:
np.average(second_arr)

50.0

In [186]:
np.average(third_arr)

55.0

In [187]:
np.min(first_arr)

10

In [188]:
np.max(first_arr)

100

In [189]:
np.mean(first_arr)

55.0

In [190]:
np.std(first_arr)

28.722813232690143

### How to get unique items and counts

In [191]:
first_arr=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [192]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [193]:
second_arr=np.array([[1, 1, 2,1] ,[ 3, 1, 2,1] , [1, 1, 2, 1], [ 7, 1, 1, 1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [194]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [195]:
np.unique(second_arr,axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [196]:
np.unique(second_arr,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [197]:
np.unique(first_arr,return_index= True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11], dtype=int64))

In [198]:
np.unique(second_arr,return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1], dtype=int64))

### Transpose like operations

In [199]:
first_2dimarr=np.arange(12).reshape((3,4))
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [200]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [201]:
second_2dimarr=np.arange(6).reshape(3,2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [202]:
np.transpose(second_2dimarr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [203]:
first_3dimarr=np.arange(24).reshape(2,3,4)
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [204]:
np.moveaxis(first_3dimarr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [205]:
np.swapaxes(first_3dimarr,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

### Reversing an array

In [206]:
arr_1dim=[10,1,9,2,8,3,7,4,6,5]
arr_1dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [207]:
arr_1dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

In [208]:
np.flip(arr_1dim)

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [209]:
arr_2dim=np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [210]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [211]:
np.flip(arr_2dim,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [212]:
arr_3dim=np.arange(24).reshape(2,3,4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [213]:
np.flip(arr_3dim,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [214]:
np.flip(arr_3dim,2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])