In [8]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [5]:
import nltk.tokenize as nt
text = "Hello everyone. Welcome to Word Tokenization"
words = nt.word_tokenize(text)
print(words) 

['Hello', 'everyone', '.', 'Welcome', 'to', 'Word', 'Tokenization']


In [6]:
import nltk.tokenize as nt

text = "Hello everyone. Welcome to Word Tokenization"
tokenizer = nt.TreebankWordTokenizer()
words = tokenizer.tokenize(text)
print(words) 

['Hello', 'everyone.', 'Welcome', 'to', 'Word', 'Tokenization']


In [9]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
print(stop_words)

{'who', 'will', 'ain', 'they', 'ma', 'such', 'her', 'wasn', 'it', 's', 'are', "won't", 'were', 'both', 'won', "you'd", 'themselves', 'needn', "should've", 'weren', 'own', 'him', 'that', "hasn't", 'mightn', 'yourselves', 'why', 'before', 'up', 'myself', 'his', 'nor', 'all', 'as', 'not', 'very', 'during', "that'll", 'hadn', 'over', 'couldn', "didn't", 'now', "hadn't", 'other', 'few', 'no', 'haven', 'our', 'aren', 'is', 'here', 'its', 'you', 'then', 'i', 'should', 'having', 'did', 'how', 'ourselves', 'does', 'he', 'below', 'itself', 'through', 'any', 'with', 'doesn', "aren't", 'wouldn', 'in', "isn't", 'be', "wouldn't", 'isn', 'if', 'whom', 'yours', "you'll", 'above', 'don', 'll', 'too', 'do', 'against', "shan't", 'an', 'doing', 'being', 'which', 'again', 'and', 'where', 'just', 're', 'd', 'theirs', 'am', 'has', 'me', 'most', 'them', "couldn't", "you've", 'can', 'those', 'yourself', 'm', "she's", 'down', 'been', 'for', 'out', 'their', "it's", "haven't", 'there', 'between', 'some', 'y', "do

In [10]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

text = "There was no chance for any character development they were busy"
stop_words = set(stopwords.words('english'))
words = word_tokenize(text) 
result = [] 
for w in words:
    if w not in stop_words:
        result.append(w)
 
print(words)
print(result)

['There', 'was', 'no', 'chance', 'for', 'any', 'character', 'development', 'they', 'were', 'busy']
['There', 'chance', 'character', 'development', 'busy']


In [11]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
ps =  PorterStemmer()
ls = LancasterStemmer()
words = ["program", "programs", "programmer", "programming", "destabilize"]
print('Porter Stemmer : ')
for w in words:
  print(w," : ",ps.stem(w))
print('\n Lancaster Stemmer : ')
for w in words:
  print(w," : ",ls.stem(w))

Porter Stemmer : 
program  :  program
programs  :  program
programmer  :  programm
programming  :  program
destabilize  :  destabil

 Lancaster Stemmer : 
program  :  program
programs  :  program
programmer  :  program
programming  :  program
destabilize  :  dest


In [12]:
import nltk 
import re
import numpy as np

text = """This movie made it into one of my top ten most awful movies.
There wasn't a continuous minute where there wasn't a fight with one monster or another. 
There was no chance for any character development, they were too busy running from one sword fight to another. 
I had no emotional attachment ( except to the big bad machine ## that wanted to destroy them)."""

data = nltk.sent_tokenize(text)
for i in range(len(data)):
  data[i] = data[i].lower()
  data[i] = re.sub(r'\W+',' ',data[i])
  data[i] = re.sub(r'\s+',' ',data[i])

for i in data:
  print(i)


this movie made it into one of my top ten most awful movies 
there wasn t a continuous minute where there wasn t a fight with one monster or another 
there was no chance for any character development they were too busy running from one sword fight to another 
i had no emotional attachment except to the big bad machine that wanted to destroy them 


In [13]:
# Creating the vocabulary for Bag of Words model
import heapq

wordcount = {}
for i in data:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in wordcount.keys():
            wordcount[word] = 1
        else:
            wordcount[word] += 1
print(len(wordcount))

freq_words = heapq.nlargest(30, wordcount, key=wordcount.get)
print(freq_words)

53
['one', 'there', 'to', 'wasn', 't', 'a', 'fight', 'another', 'no', 'this', 'movie', 'made', 'it', 'into', 'of', 'my', 'top', 'ten', 'most', 'awful', 'movies', 'continuous', 'minute', 'where', 'with', 'monster', 'or', 'was', 'chance', 'for']


In [14]:
X = []
for i in data:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(i):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)
X = np.asarray(X)
print(X)

[[1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [39]:
import nltk
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text = "this is an example to extract n-grams"

# function to generate n-grams 
def extract_ngrams(data, num):
    n_grams = ngrams(nltk.word_tokenize(data), num)
    return [ ' '.join(grams) for grams in n_grams]

# 4-grams 
print(extract_ngrams(text,4))
# 5-grams
print(extract_ngrams(text,5))

['this is an example', 'is an example to', 'an example to extract', 'example to extract n-grams']
['this is an example to', 'is an example to extract', 'an example to extract n-grams']


In [34]:
import nltk
from nltk.util import ngrams
 
# Function to generate n-grams from sentences.
def extract_ngrams(data, num):
    n_grams = ngrams(nltk.word_tokenize(data), num)
    return [ ' '.join(grams) for grams in n_grams]
 
data = 'A class is a blueprint for the object.'
 
print("1-gram: ", extract_ngrams(data, 1))
print("2-gram: ", extract_ngrams(data, 2))
print("3-gram: ", extract_ngrams(data, 3))
print("4-gram: ", extract_ngrams(data, 4))

1-gram:  ['A', 'class', 'is', 'a', 'blueprint', 'for', 'the', 'object', '.']
2-gram:  ['A class', 'class is', 'is a', 'a blueprint', 'blueprint for', 'for the', 'the object', 'object .']
3-gram:  ['A class is', 'class is a', 'is a blueprint', 'a blueprint for', 'blueprint for the', 'for the object', 'the object .']
4-gram:  ['A class is a', 'class is a blueprint', 'is a blueprint for', 'a blueprint for the', 'blueprint for the object', 'for the object .']
