### Arithmetic operations

In [1]:
import numpy as np

In [2]:
a=np.arange(1,11)
b=np.arange(21,31)
print("a",a)
print("b",b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [3]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [4]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [5]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [6]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [7]:
a**b

array([                  1,             4194304,         94143178827,
           281474976710656,  298023223876953125, 4561031516192243712,
       5059972980857283351,                   0, 5756027422282277481,
       5076944270305263616])

In [8]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [12]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [13]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [14]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [15]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [16]:
np.power(a,b)

array([                  1,             4194304,         94143178827,
           281474976710656,  298023223876953125, 4561031516192243712,
       5059972980857283351,                   0, 5756027422282277481,
       5076944270305263616])

In [17]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])